# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: healthcheck.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11healthcheck.proto\"_\n\x11PingHealthSOToMSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\x12\x19\n\x11\x61\x63tiveSimulations\x18\x03 \x03(\t\"D\n\x11PongHealthMSOToSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\"G\n\x14PingHealthMSOToModel\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\"z\n\x14PongHealthModelToMSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\x12\x14\n\x0cnumberOfBids\x18\x03 \x01(\x05\x12\x1b\n\x13numberOfAllocations\x18\x04 \x01(\x05**\n\x0cHealthStatus\x12\x0b\n\x07HEALTHY\x10\x00\x12\r\n\tUNHEALTHY\x10\x01\x42\x37\n&nl.tno.simulation.externalmodel.protosB\x0bHealthcheckP\x01\x62\x06proto3')

_HEALTHSTATUS = DESCRIPTOR.enum_types_by_name['HealthStatus']
HealthStatus = enum_type_wrapper.EnumTypeWrapper(_HEALTHSTATUS)
HEALTHY = 0
UNHEALTHY = 1


_PINGHEALTHSOTOMSO = DESCRIPTOR.message_types_by_name['PingHealthSOToMSO']
_PONGHEALTHMSOTOSO = DESCRIPTOR.message_types_by_name['PongHealthMSOToSO']
_PINGHEALTHMSOTOMODEL = DESCRIPTOR.message_types_by_name['PingHealthMSOToModel']
_PONGHEALTHMODELTOMSO = DESCRIPTOR.message_types_by_name['PongHealthModelToMSO']
PingHealthSOToMSO = _reflection.GeneratedProtocolMessageType('PingHealthSOToMSO', (_message.Message,), {
  'DESCRIPTOR' : _PINGHEALTHSOTOMSO,
  '__module__' : 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PingHealthSOToMSO)
  })
_sym_db.RegisterMessage(PingHealthSOToMSO)

PongHealthMSOToSO = _reflection.GeneratedProtocolMessageType('PongHealthMSOToSO', (_message.Message,), {
  'DESCRIPTOR' : _PONGHEALTHMSOTOSO,
  '__module__' : 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PongHealthMSOToSO)
  })
_sym_db.RegisterMessage(PongHealthMSOToSO)

PingHealthMSOToModel = _reflection.GeneratedProtocolMessageType('PingHealthMSOToModel', (_message.Message,), {
  'DESCRIPTOR' : _PINGHEALTHMSOTOMODEL,
  '__module__' : 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PingHealthMSOToModel)
  })
_sym_db.RegisterMessage(PingHealthMSOToModel)

PongHealthModelToMSO = _reflection.GeneratedProtocolMessageType('PongHealthModelToMSO', (_message.Message,), {
  'DESCRIPTOR' : _PONGHEALTHMODELTOMSO,
  '__module__' : 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PongHealthModelToMSO)
  })
_sym_db.RegisterMessage(PongHealthModelToMSO)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&nl.tno.simulation.externalmodel.protosB\013HealthcheckP\001'
  _HEALTHSTATUS._serialized_start=385
  _HEALTHSTATUS._serialized_end=427
  _PINGHEALTHSOTOMSO._serialized_start=21
  _PINGHEALTHSOTOMSO._serialized_end=116
  _PONGHEALTHMSOTOSO._serialized_start=118
  _PONGHEALTHMSOTOSO._serialized_end=186
  _PINGHEALTHMSOTOMODEL._serialized_start=188
  _PINGHEALTHMSOTOMODEL._serialized_end=259
  _PONGHEALTHMODELTOMSO._serialized_start=261
  _PONGHEALTHMODELTOMSO._serialized_end=383
# @@protoc_insertion_point(module_scope)
