// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

public interface AllModelsHaveTerminatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllModelsHaveTerminated)
    com.google.protobuf.MessageOrBuilder {
}
