// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

public interface DeployModelsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeployModels)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string simulatorId = 1;</code>
   * @return The simulatorId.
   */
  java.lang.String getSimulatorId();
  /**
   * <code>string simulatorId = 1;</code>
   * @return The bytes for simulatorId.
   */
  com.google.protobuf.ByteString
      getSimulatorIdBytes();

  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  java.util.List<nl.tno.simulation.externalmodel.protos.ModelConfiguration> 
      getModelConfigurationsList();
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  nl.tno.simulation.externalmodel.protos.ModelConfiguration getModelConfigurations(int index);
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  int getModelConfigurationsCount();
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  java.util.List<? extends nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder> 
      getModelConfigurationsOrBuilderList();
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder getModelConfigurationsOrBuilder(
      int index);

  /**
   * <code>double keepLogsHours = 3;</code>
   * @return The keepLogsHours.
   */
  double getKeepLogsHours();
}
