// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

/**
 * Protobuf type {@code DeployModels}
 */
public final class DeployModels extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DeployModels)
    DeployModelsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeployModels.newBuilder() to construct.
  private DeployModels(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeployModels() {
    simulatorId_ = "";
    modelConfigurations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeployModels();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeployModels(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            simulatorId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              modelConfigurations_ = new java.util.ArrayList<nl.tno.simulation.externalmodel.protos.ModelConfiguration>();
              mutable_bitField0_ |= 0x00000001;
            }
            modelConfigurations_.add(
                input.readMessage(nl.tno.simulation.externalmodel.protos.ModelConfiguration.parser(), extensionRegistry));
            break;
          }
          case 25: {

            keepLogsHours_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        modelConfigurations_ = java.util.Collections.unmodifiableList(modelConfigurations_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_DeployModels_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_DeployModels_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            nl.tno.simulation.externalmodel.protos.DeployModels.class, nl.tno.simulation.externalmodel.protos.DeployModels.Builder.class);
  }

  public static final int SIMULATORID_FIELD_NUMBER = 1;
  private volatile java.lang.Object simulatorId_;
  /**
   * <code>string simulatorId = 1;</code>
   * @return The simulatorId.
   */
  @java.lang.Override
  public java.lang.String getSimulatorId() {
    java.lang.Object ref = simulatorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      simulatorId_ = s;
      return s;
    }
  }
  /**
   * <code>string simulatorId = 1;</code>
   * @return The bytes for simulatorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSimulatorIdBytes() {
    java.lang.Object ref = simulatorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      simulatorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODELCONFIGURATIONS_FIELD_NUMBER = 2;
  private java.util.List<nl.tno.simulation.externalmodel.protos.ModelConfiguration> modelConfigurations_;
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  @java.lang.Override
  public java.util.List<nl.tno.simulation.externalmodel.protos.ModelConfiguration> getModelConfigurationsList() {
    return modelConfigurations_;
  }
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder> 
      getModelConfigurationsOrBuilderList() {
    return modelConfigurations_;
  }
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  @java.lang.Override
  public int getModelConfigurationsCount() {
    return modelConfigurations_.size();
  }
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  @java.lang.Override
  public nl.tno.simulation.externalmodel.protos.ModelConfiguration getModelConfigurations(int index) {
    return modelConfigurations_.get(index);
  }
  /**
   * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
   */
  @java.lang.Override
  public nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder getModelConfigurationsOrBuilder(
      int index) {
    return modelConfigurations_.get(index);
  }

  public static final int KEEPLOGSHOURS_FIELD_NUMBER = 3;
  private double keepLogsHours_;
  /**
   * <code>double keepLogsHours = 3;</code>
   * @return The keepLogsHours.
   */
  @java.lang.Override
  public double getKeepLogsHours() {
    return keepLogsHours_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(simulatorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, simulatorId_);
    }
    for (int i = 0; i < modelConfigurations_.size(); i++) {
      output.writeMessage(2, modelConfigurations_.get(i));
    }
    if (java.lang.Double.doubleToRawLongBits(keepLogsHours_) != 0) {
      output.writeDouble(3, keepLogsHours_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(simulatorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, simulatorId_);
    }
    for (int i = 0; i < modelConfigurations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, modelConfigurations_.get(i));
    }
    if (java.lang.Double.doubleToRawLongBits(keepLogsHours_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, keepLogsHours_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof nl.tno.simulation.externalmodel.protos.DeployModels)) {
      return super.equals(obj);
    }
    nl.tno.simulation.externalmodel.protos.DeployModels other = (nl.tno.simulation.externalmodel.protos.DeployModels) obj;

    if (!getSimulatorId()
        .equals(other.getSimulatorId())) return false;
    if (!getModelConfigurationsList()
        .equals(other.getModelConfigurationsList())) return false;
    if (java.lang.Double.doubleToLongBits(getKeepLogsHours())
        != java.lang.Double.doubleToLongBits(
            other.getKeepLogsHours())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIMULATORID_FIELD_NUMBER;
    hash = (53 * hash) + getSimulatorId().hashCode();
    if (getModelConfigurationsCount() > 0) {
      hash = (37 * hash) + MODELCONFIGURATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getModelConfigurationsList().hashCode();
    }
    hash = (37 * hash) + KEEPLOGSHOURS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getKeepLogsHours()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.DeployModels parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(nl.tno.simulation.externalmodel.protos.DeployModels prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DeployModels}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DeployModels)
      nl.tno.simulation.externalmodel.protos.DeployModelsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_DeployModels_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_DeployModels_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tno.simulation.externalmodel.protos.DeployModels.class, nl.tno.simulation.externalmodel.protos.DeployModels.Builder.class);
    }

    // Construct using nl.tno.simulation.externalmodel.protos.DeployModels.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getModelConfigurationsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      simulatorId_ = "";

      if (modelConfigurationsBuilder_ == null) {
        modelConfigurations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        modelConfigurationsBuilder_.clear();
      }
      keepLogsHours_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_DeployModels_descriptor;
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.DeployModels getDefaultInstanceForType() {
      return nl.tno.simulation.externalmodel.protos.DeployModels.getDefaultInstance();
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.DeployModels build() {
      nl.tno.simulation.externalmodel.protos.DeployModels result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.DeployModels buildPartial() {
      nl.tno.simulation.externalmodel.protos.DeployModels result = new nl.tno.simulation.externalmodel.protos.DeployModels(this);
      int from_bitField0_ = bitField0_;
      result.simulatorId_ = simulatorId_;
      if (modelConfigurationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          modelConfigurations_ = java.util.Collections.unmodifiableList(modelConfigurations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.modelConfigurations_ = modelConfigurations_;
      } else {
        result.modelConfigurations_ = modelConfigurationsBuilder_.build();
      }
      result.keepLogsHours_ = keepLogsHours_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof nl.tno.simulation.externalmodel.protos.DeployModels) {
        return mergeFrom((nl.tno.simulation.externalmodel.protos.DeployModels)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(nl.tno.simulation.externalmodel.protos.DeployModels other) {
      if (other == nl.tno.simulation.externalmodel.protos.DeployModels.getDefaultInstance()) return this;
      if (!other.getSimulatorId().isEmpty()) {
        simulatorId_ = other.simulatorId_;
        onChanged();
      }
      if (modelConfigurationsBuilder_ == null) {
        if (!other.modelConfigurations_.isEmpty()) {
          if (modelConfigurations_.isEmpty()) {
            modelConfigurations_ = other.modelConfigurations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureModelConfigurationsIsMutable();
            modelConfigurations_.addAll(other.modelConfigurations_);
          }
          onChanged();
        }
      } else {
        if (!other.modelConfigurations_.isEmpty()) {
          if (modelConfigurationsBuilder_.isEmpty()) {
            modelConfigurationsBuilder_.dispose();
            modelConfigurationsBuilder_ = null;
            modelConfigurations_ = other.modelConfigurations_;
            bitField0_ = (bitField0_ & ~0x00000001);
            modelConfigurationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getModelConfigurationsFieldBuilder() : null;
          } else {
            modelConfigurationsBuilder_.addAllMessages(other.modelConfigurations_);
          }
        }
      }
      if (other.getKeepLogsHours() != 0D) {
        setKeepLogsHours(other.getKeepLogsHours());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      nl.tno.simulation.externalmodel.protos.DeployModels parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (nl.tno.simulation.externalmodel.protos.DeployModels) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object simulatorId_ = "";
    /**
     * <code>string simulatorId = 1;</code>
     * @return The simulatorId.
     */
    public java.lang.String getSimulatorId() {
      java.lang.Object ref = simulatorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        simulatorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string simulatorId = 1;</code>
     * @return The bytes for simulatorId.
     */
    public com.google.protobuf.ByteString
        getSimulatorIdBytes() {
      java.lang.Object ref = simulatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        simulatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string simulatorId = 1;</code>
     * @param value The simulatorId to set.
     * @return This builder for chaining.
     */
    public Builder setSimulatorId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      simulatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string simulatorId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSimulatorId() {
      
      simulatorId_ = getDefaultInstance().getSimulatorId();
      onChanged();
      return this;
    }
    /**
     * <code>string simulatorId = 1;</code>
     * @param value The bytes for simulatorId to set.
     * @return This builder for chaining.
     */
    public Builder setSimulatorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      simulatorId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<nl.tno.simulation.externalmodel.protos.ModelConfiguration> modelConfigurations_ =
      java.util.Collections.emptyList();
    private void ensureModelConfigurationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        modelConfigurations_ = new java.util.ArrayList<nl.tno.simulation.externalmodel.protos.ModelConfiguration>(modelConfigurations_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        nl.tno.simulation.externalmodel.protos.ModelConfiguration, nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder, nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder> modelConfigurationsBuilder_;

    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public java.util.List<nl.tno.simulation.externalmodel.protos.ModelConfiguration> getModelConfigurationsList() {
      if (modelConfigurationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(modelConfigurations_);
      } else {
        return modelConfigurationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public int getModelConfigurationsCount() {
      if (modelConfigurationsBuilder_ == null) {
        return modelConfigurations_.size();
      } else {
        return modelConfigurationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public nl.tno.simulation.externalmodel.protos.ModelConfiguration getModelConfigurations(int index) {
      if (modelConfigurationsBuilder_ == null) {
        return modelConfigurations_.get(index);
      } else {
        return modelConfigurationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder setModelConfigurations(
        int index, nl.tno.simulation.externalmodel.protos.ModelConfiguration value) {
      if (modelConfigurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelConfigurationsIsMutable();
        modelConfigurations_.set(index, value);
        onChanged();
      } else {
        modelConfigurationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder setModelConfigurations(
        int index, nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder builderForValue) {
      if (modelConfigurationsBuilder_ == null) {
        ensureModelConfigurationsIsMutable();
        modelConfigurations_.set(index, builderForValue.build());
        onChanged();
      } else {
        modelConfigurationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder addModelConfigurations(nl.tno.simulation.externalmodel.protos.ModelConfiguration value) {
      if (modelConfigurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelConfigurationsIsMutable();
        modelConfigurations_.add(value);
        onChanged();
      } else {
        modelConfigurationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder addModelConfigurations(
        int index, nl.tno.simulation.externalmodel.protos.ModelConfiguration value) {
      if (modelConfigurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureModelConfigurationsIsMutable();
        modelConfigurations_.add(index, value);
        onChanged();
      } else {
        modelConfigurationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder addModelConfigurations(
        nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder builderForValue) {
      if (modelConfigurationsBuilder_ == null) {
        ensureModelConfigurationsIsMutable();
        modelConfigurations_.add(builderForValue.build());
        onChanged();
      } else {
        modelConfigurationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder addModelConfigurations(
        int index, nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder builderForValue) {
      if (modelConfigurationsBuilder_ == null) {
        ensureModelConfigurationsIsMutable();
        modelConfigurations_.add(index, builderForValue.build());
        onChanged();
      } else {
        modelConfigurationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder addAllModelConfigurations(
        java.lang.Iterable<? extends nl.tno.simulation.externalmodel.protos.ModelConfiguration> values) {
      if (modelConfigurationsBuilder_ == null) {
        ensureModelConfigurationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, modelConfigurations_);
        onChanged();
      } else {
        modelConfigurationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder clearModelConfigurations() {
      if (modelConfigurationsBuilder_ == null) {
        modelConfigurations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        modelConfigurationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public Builder removeModelConfigurations(int index) {
      if (modelConfigurationsBuilder_ == null) {
        ensureModelConfigurationsIsMutable();
        modelConfigurations_.remove(index);
        onChanged();
      } else {
        modelConfigurationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder getModelConfigurationsBuilder(
        int index) {
      return getModelConfigurationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder getModelConfigurationsOrBuilder(
        int index) {
      if (modelConfigurationsBuilder_ == null) {
        return modelConfigurations_.get(index);  } else {
        return modelConfigurationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public java.util.List<? extends nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder> 
         getModelConfigurationsOrBuilderList() {
      if (modelConfigurationsBuilder_ != null) {
        return modelConfigurationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(modelConfigurations_);
      }
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder addModelConfigurationsBuilder() {
      return getModelConfigurationsFieldBuilder().addBuilder(
          nl.tno.simulation.externalmodel.protos.ModelConfiguration.getDefaultInstance());
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder addModelConfigurationsBuilder(
        int index) {
      return getModelConfigurationsFieldBuilder().addBuilder(
          index, nl.tno.simulation.externalmodel.protos.ModelConfiguration.getDefaultInstance());
    }
    /**
     * <code>repeated .ModelConfiguration modelConfigurations = 2;</code>
     */
    public java.util.List<nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder> 
         getModelConfigurationsBuilderList() {
      return getModelConfigurationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        nl.tno.simulation.externalmodel.protos.ModelConfiguration, nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder, nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder> 
        getModelConfigurationsFieldBuilder() {
      if (modelConfigurationsBuilder_ == null) {
        modelConfigurationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            nl.tno.simulation.externalmodel.protos.ModelConfiguration, nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder, nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder>(
                modelConfigurations_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        modelConfigurations_ = null;
      }
      return modelConfigurationsBuilder_;
    }

    private double keepLogsHours_ ;
    /**
     * <code>double keepLogsHours = 3;</code>
     * @return The keepLogsHours.
     */
    @java.lang.Override
    public double getKeepLogsHours() {
      return keepLogsHours_;
    }
    /**
     * <code>double keepLogsHours = 3;</code>
     * @param value The keepLogsHours to set.
     * @return This builder for chaining.
     */
    public Builder setKeepLogsHours(double value) {
      
      keepLogsHours_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double keepLogsHours = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeepLogsHours() {
      
      keepLogsHours_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DeployModels)
  }

  // @@protoc_insertion_point(class_scope:DeployModels)
  private static final nl.tno.simulation.externalmodel.protos.DeployModels DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new nl.tno.simulation.externalmodel.protos.DeployModels();
  }

  public static nl.tno.simulation.externalmodel.protos.DeployModels getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeployModels>
      PARSER = new com.google.protobuf.AbstractParser<DeployModels>() {
    @java.lang.Override
    public DeployModels parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeployModels(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeployModels> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeployModels> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public nl.tno.simulation.externalmodel.protos.DeployModels getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

