// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

public interface ErrorOccurredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrorOccurred)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error_message = 1;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 1;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
