// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthcheck.proto

package nl.tno.simulation.externalmodel.protos;

public final class Healthcheck {
  private Healthcheck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingHealthSOToMSO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingHealthSOToMSO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PongHealthMSOToSO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PongHealthMSOToSO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PingHealthMSOToModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PingHealthMSOToModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PongHealthModelToMSO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PongHealthModelToMSO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021healthcheck.proto\"_\n\021PingHealthSOToMSO" +
      "\022\036\n\007healthy\030\001 \001(\0162\r.HealthStatus\022\017\n\007reas" +
      "ons\030\002 \003(\t\022\031\n\021activeSimulations\030\003 \003(\t\"D\n\021" +
      "PongHealthMSOToSO\022\036\n\007healthy\030\001 \001(\0162\r.Hea" +
      "lthStatus\022\017\n\007reasons\030\002 \003(\t\"G\n\024PingHealth" +
      "MSOToModel\022\036\n\007healthy\030\001 \001(\0162\r.HealthStat" +
      "us\022\017\n\007reasons\030\002 \003(\t\"z\n\024PongHealthModelTo" +
      "MSO\022\036\n\007healthy\030\001 \001(\0162\r.HealthStatus\022\017\n\007r" +
      "easons\030\002 \003(\t\022\024\n\014numberOfBids\030\003 \001(\005\022\033\n\023nu" +
      "mberOfAllocations\030\004 \001(\005**\n\014HealthStatus\022" +
      "\013\n\007HEALTHY\020\000\022\r\n\tUNHEALTHY\020\001B7\n&nl.tno.si" +
      "mulation.externalmodel.protosB\013Healthche" +
      "ckP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PingHealthSOToMSO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PingHealthSOToMSO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingHealthSOToMSO_descriptor,
        new java.lang.String[] { "Healthy", "Reasons", "ActiveSimulations", });
    internal_static_PongHealthMSOToSO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PongHealthMSOToSO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PongHealthMSOToSO_descriptor,
        new java.lang.String[] { "Healthy", "Reasons", });
    internal_static_PingHealthMSOToModel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PingHealthMSOToModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PingHealthMSOToModel_descriptor,
        new java.lang.String[] { "Healthy", "Reasons", });
    internal_static_PongHealthModelToMSO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PongHealthModelToMSO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PongHealthModelToMSO_descriptor,
        new java.lang.String[] { "Healthy", "Reasons", "NumberOfBids", "NumberOfAllocations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
