// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

/**
 * Protobuf type {@code ModelConfiguration}
 */
public final class ModelConfiguration extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ModelConfiguration)
    ModelConfigurationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModelConfiguration.newBuilder() to construct.
  private ModelConfiguration(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelConfiguration() {
    modelID_ = "";
    imageUrl_ = "";
    environmentVariables_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ModelConfiguration();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ModelConfiguration(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            modelID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            imageUrl_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              environmentVariables_ = new java.util.ArrayList<nl.tno.simulation.externalmodel.protos.EnvironmentVariable>();
              mutable_bitField0_ |= 0x00000001;
            }
            environmentVariables_.add(
                input.readMessage(nl.tno.simulation.externalmodel.protos.EnvironmentVariable.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        environmentVariables_ = java.util.Collections.unmodifiableList(environmentVariables_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_ModelConfiguration_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_ModelConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            nl.tno.simulation.externalmodel.protos.ModelConfiguration.class, nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder.class);
  }

  public static final int MODELID_FIELD_NUMBER = 1;
  private volatile java.lang.Object modelID_;
  /**
   * <code>string modelID = 1;</code>
   * @return The modelID.
   */
  @java.lang.Override
  public java.lang.String getModelID() {
    java.lang.Object ref = modelID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelID_ = s;
      return s;
    }
  }
  /**
   * <code>string modelID = 1;</code>
   * @return The bytes for modelID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelIDBytes() {
    java.lang.Object ref = modelID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGEURL_FIELD_NUMBER = 2;
  private volatile java.lang.Object imageUrl_;
  /**
   * <pre>
   * Including hostname, port &amp; container name
   * </pre>
   *
   * <code>string imageUrl = 2;</code>
   * @return The imageUrl.
   */
  @java.lang.Override
  public java.lang.String getImageUrl() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Including hostname, port &amp; container name
   * </pre>
   *
   * <code>string imageUrl = 2;</code>
   * @return The bytes for imageUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageUrlBytes() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENVIRONMENTVARIABLES_FIELD_NUMBER = 3;
  private java.util.List<nl.tno.simulation.externalmodel.protos.EnvironmentVariable> environmentVariables_;
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  @java.lang.Override
  public java.util.List<nl.tno.simulation.externalmodel.protos.EnvironmentVariable> getEnvironmentVariablesList() {
    return environmentVariables_;
  }
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder> 
      getEnvironmentVariablesOrBuilderList() {
    return environmentVariables_;
  }
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  @java.lang.Override
  public int getEnvironmentVariablesCount() {
    return environmentVariables_.size();
  }
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  @java.lang.Override
  public nl.tno.simulation.externalmodel.protos.EnvironmentVariable getEnvironmentVariables(int index) {
    return environmentVariables_.get(index);
  }
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  @java.lang.Override
  public nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder getEnvironmentVariablesOrBuilder(
      int index) {
    return environmentVariables_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, modelID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageUrl_);
    }
    for (int i = 0; i < environmentVariables_.size(); i++) {
      output.writeMessage(3, environmentVariables_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, modelID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageUrl_);
    }
    for (int i = 0; i < environmentVariables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, environmentVariables_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof nl.tno.simulation.externalmodel.protos.ModelConfiguration)) {
      return super.equals(obj);
    }
    nl.tno.simulation.externalmodel.protos.ModelConfiguration other = (nl.tno.simulation.externalmodel.protos.ModelConfiguration) obj;

    if (!getModelID()
        .equals(other.getModelID())) return false;
    if (!getImageUrl()
        .equals(other.getImageUrl())) return false;
    if (!getEnvironmentVariablesList()
        .equals(other.getEnvironmentVariablesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODELID_FIELD_NUMBER;
    hash = (53 * hash) + getModelID().hashCode();
    hash = (37 * hash) + IMAGEURL_FIELD_NUMBER;
    hash = (53 * hash) + getImageUrl().hashCode();
    if (getEnvironmentVariablesCount() > 0) {
      hash = (37 * hash) + ENVIRONMENTVARIABLES_FIELD_NUMBER;
      hash = (53 * hash) + getEnvironmentVariablesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(nl.tno.simulation.externalmodel.protos.ModelConfiguration prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ModelConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ModelConfiguration)
      nl.tno.simulation.externalmodel.protos.ModelConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_ModelConfiguration_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_ModelConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tno.simulation.externalmodel.protos.ModelConfiguration.class, nl.tno.simulation.externalmodel.protos.ModelConfiguration.Builder.class);
    }

    // Construct using nl.tno.simulation.externalmodel.protos.ModelConfiguration.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEnvironmentVariablesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      modelID_ = "";

      imageUrl_ = "";

      if (environmentVariablesBuilder_ == null) {
        environmentVariables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        environmentVariablesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return nl.tno.simulation.externalmodel.protos.Lifecycle.internal_static_ModelConfiguration_descriptor;
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.ModelConfiguration getDefaultInstanceForType() {
      return nl.tno.simulation.externalmodel.protos.ModelConfiguration.getDefaultInstance();
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.ModelConfiguration build() {
      nl.tno.simulation.externalmodel.protos.ModelConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.ModelConfiguration buildPartial() {
      nl.tno.simulation.externalmodel.protos.ModelConfiguration result = new nl.tno.simulation.externalmodel.protos.ModelConfiguration(this);
      int from_bitField0_ = bitField0_;
      result.modelID_ = modelID_;
      result.imageUrl_ = imageUrl_;
      if (environmentVariablesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          environmentVariables_ = java.util.Collections.unmodifiableList(environmentVariables_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.environmentVariables_ = environmentVariables_;
      } else {
        result.environmentVariables_ = environmentVariablesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof nl.tno.simulation.externalmodel.protos.ModelConfiguration) {
        return mergeFrom((nl.tno.simulation.externalmodel.protos.ModelConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(nl.tno.simulation.externalmodel.protos.ModelConfiguration other) {
      if (other == nl.tno.simulation.externalmodel.protos.ModelConfiguration.getDefaultInstance()) return this;
      if (!other.getModelID().isEmpty()) {
        modelID_ = other.modelID_;
        onChanged();
      }
      if (!other.getImageUrl().isEmpty()) {
        imageUrl_ = other.imageUrl_;
        onChanged();
      }
      if (environmentVariablesBuilder_ == null) {
        if (!other.environmentVariables_.isEmpty()) {
          if (environmentVariables_.isEmpty()) {
            environmentVariables_ = other.environmentVariables_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEnvironmentVariablesIsMutable();
            environmentVariables_.addAll(other.environmentVariables_);
          }
          onChanged();
        }
      } else {
        if (!other.environmentVariables_.isEmpty()) {
          if (environmentVariablesBuilder_.isEmpty()) {
            environmentVariablesBuilder_.dispose();
            environmentVariablesBuilder_ = null;
            environmentVariables_ = other.environmentVariables_;
            bitField0_ = (bitField0_ & ~0x00000001);
            environmentVariablesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEnvironmentVariablesFieldBuilder() : null;
          } else {
            environmentVariablesBuilder_.addAllMessages(other.environmentVariables_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      nl.tno.simulation.externalmodel.protos.ModelConfiguration parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (nl.tno.simulation.externalmodel.protos.ModelConfiguration) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object modelID_ = "";
    /**
     * <code>string modelID = 1;</code>
     * @return The modelID.
     */
    public java.lang.String getModelID() {
      java.lang.Object ref = modelID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string modelID = 1;</code>
     * @return The bytes for modelID.
     */
    public com.google.protobuf.ByteString
        getModelIDBytes() {
      java.lang.Object ref = modelID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string modelID = 1;</code>
     * @param value The modelID to set.
     * @return This builder for chaining.
     */
    public Builder setModelID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modelID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string modelID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelID() {
      
      modelID_ = getDefaultInstance().getModelID();
      onChanged();
      return this;
    }
    /**
     * <code>string modelID = 1;</code>
     * @param value The bytes for modelID to set.
     * @return This builder for chaining.
     */
    public Builder setModelIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modelID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imageUrl_ = "";
    /**
     * <pre>
     * Including hostname, port &amp; container name
     * </pre>
     *
     * <code>string imageUrl = 2;</code>
     * @return The imageUrl.
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Including hostname, port &amp; container name
     * </pre>
     *
     * <code>string imageUrl = 2;</code>
     * @return The bytes for imageUrl.
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Including hostname, port &amp; container name
     * </pre>
     *
     * <code>string imageUrl = 2;</code>
     * @param value The imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Including hostname, port &amp; container name
     * </pre>
     *
     * <code>string imageUrl = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearImageUrl() {
      
      imageUrl_ = getDefaultInstance().getImageUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Including hostname, port &amp; container name
     * </pre>
     *
     * <code>string imageUrl = 2;</code>
     * @param value The bytes for imageUrl to set.
     * @return This builder for chaining.
     */
    public Builder setImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageUrl_ = value;
      onChanged();
      return this;
    }

    private java.util.List<nl.tno.simulation.externalmodel.protos.EnvironmentVariable> environmentVariables_ =
      java.util.Collections.emptyList();
    private void ensureEnvironmentVariablesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        environmentVariables_ = new java.util.ArrayList<nl.tno.simulation.externalmodel.protos.EnvironmentVariable>(environmentVariables_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        nl.tno.simulation.externalmodel.protos.EnvironmentVariable, nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder, nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder> environmentVariablesBuilder_;

    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public java.util.List<nl.tno.simulation.externalmodel.protos.EnvironmentVariable> getEnvironmentVariablesList() {
      if (environmentVariablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(environmentVariables_);
      } else {
        return environmentVariablesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public int getEnvironmentVariablesCount() {
      if (environmentVariablesBuilder_ == null) {
        return environmentVariables_.size();
      } else {
        return environmentVariablesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public nl.tno.simulation.externalmodel.protos.EnvironmentVariable getEnvironmentVariables(int index) {
      if (environmentVariablesBuilder_ == null) {
        return environmentVariables_.get(index);
      } else {
        return environmentVariablesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder setEnvironmentVariables(
        int index, nl.tno.simulation.externalmodel.protos.EnvironmentVariable value) {
      if (environmentVariablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnvironmentVariablesIsMutable();
        environmentVariables_.set(index, value);
        onChanged();
      } else {
        environmentVariablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder setEnvironmentVariables(
        int index, nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder builderForValue) {
      if (environmentVariablesBuilder_ == null) {
        ensureEnvironmentVariablesIsMutable();
        environmentVariables_.set(index, builderForValue.build());
        onChanged();
      } else {
        environmentVariablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder addEnvironmentVariables(nl.tno.simulation.externalmodel.protos.EnvironmentVariable value) {
      if (environmentVariablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnvironmentVariablesIsMutable();
        environmentVariables_.add(value);
        onChanged();
      } else {
        environmentVariablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder addEnvironmentVariables(
        int index, nl.tno.simulation.externalmodel.protos.EnvironmentVariable value) {
      if (environmentVariablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnvironmentVariablesIsMutable();
        environmentVariables_.add(index, value);
        onChanged();
      } else {
        environmentVariablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder addEnvironmentVariables(
        nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder builderForValue) {
      if (environmentVariablesBuilder_ == null) {
        ensureEnvironmentVariablesIsMutable();
        environmentVariables_.add(builderForValue.build());
        onChanged();
      } else {
        environmentVariablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder addEnvironmentVariables(
        int index, nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder builderForValue) {
      if (environmentVariablesBuilder_ == null) {
        ensureEnvironmentVariablesIsMutable();
        environmentVariables_.add(index, builderForValue.build());
        onChanged();
      } else {
        environmentVariablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder addAllEnvironmentVariables(
        java.lang.Iterable<? extends nl.tno.simulation.externalmodel.protos.EnvironmentVariable> values) {
      if (environmentVariablesBuilder_ == null) {
        ensureEnvironmentVariablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, environmentVariables_);
        onChanged();
      } else {
        environmentVariablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder clearEnvironmentVariables() {
      if (environmentVariablesBuilder_ == null) {
        environmentVariables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        environmentVariablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public Builder removeEnvironmentVariables(int index) {
      if (environmentVariablesBuilder_ == null) {
        ensureEnvironmentVariablesIsMutable();
        environmentVariables_.remove(index);
        onChanged();
      } else {
        environmentVariablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder getEnvironmentVariablesBuilder(
        int index) {
      return getEnvironmentVariablesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder getEnvironmentVariablesOrBuilder(
        int index) {
      if (environmentVariablesBuilder_ == null) {
        return environmentVariables_.get(index);  } else {
        return environmentVariablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public java.util.List<? extends nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder> 
         getEnvironmentVariablesOrBuilderList() {
      if (environmentVariablesBuilder_ != null) {
        return environmentVariablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(environmentVariables_);
      }
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder addEnvironmentVariablesBuilder() {
      return getEnvironmentVariablesFieldBuilder().addBuilder(
          nl.tno.simulation.externalmodel.protos.EnvironmentVariable.getDefaultInstance());
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder addEnvironmentVariablesBuilder(
        int index) {
      return getEnvironmentVariablesFieldBuilder().addBuilder(
          index, nl.tno.simulation.externalmodel.protos.EnvironmentVariable.getDefaultInstance());
    }
    /**
     * <pre>
     * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
     * </pre>
     *
     * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
     */
    public java.util.List<nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder> 
         getEnvironmentVariablesBuilderList() {
      return getEnvironmentVariablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        nl.tno.simulation.externalmodel.protos.EnvironmentVariable, nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder, nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder> 
        getEnvironmentVariablesFieldBuilder() {
      if (environmentVariablesBuilder_ == null) {
        environmentVariablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            nl.tno.simulation.externalmodel.protos.EnvironmentVariable, nl.tno.simulation.externalmodel.protos.EnvironmentVariable.Builder, nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder>(
                environmentVariables_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        environmentVariables_ = null;
      }
      return environmentVariablesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ModelConfiguration)
  }

  // @@protoc_insertion_point(class_scope:ModelConfiguration)
  private static final nl.tno.simulation.externalmodel.protos.ModelConfiguration DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new nl.tno.simulation.externalmodel.protos.ModelConfiguration();
  }

  public static nl.tno.simulation.externalmodel.protos.ModelConfiguration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelConfiguration>
      PARSER = new com.google.protobuf.AbstractParser<ModelConfiguration>() {
    @java.lang.Override
    public ModelConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ModelConfiguration(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModelConfiguration> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelConfiguration> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public nl.tno.simulation.externalmodel.protos.ModelConfiguration getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

