// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

public interface ModelConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModelConfiguration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string modelID = 1;</code>
   * @return The modelID.
   */
  java.lang.String getModelID();
  /**
   * <code>string modelID = 1;</code>
   * @return The bytes for modelID.
   */
  com.google.protobuf.ByteString
      getModelIDBytes();

  /**
   * <pre>
   * Including hostname, port &amp; container name
   * </pre>
   *
   * <code>string imageUrl = 2;</code>
   * @return The imageUrl.
   */
  java.lang.String getImageUrl();
  /**
   * <pre>
   * Including hostname, port &amp; container name
   * </pre>
   *
   * <code>string imageUrl = 2;</code>
   * @return The bytes for imageUrl.
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  java.util.List<nl.tno.simulation.externalmodel.protos.EnvironmentVariable> 
      getEnvironmentVariablesList();
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  nl.tno.simulation.externalmodel.protos.EnvironmentVariable getEnvironmentVariables(int index);
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  int getEnvironmentVariablesCount();
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  java.util.List<? extends nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder> 
      getEnvironmentVariablesOrBuilderList();
  /**
   * <pre>
   * Contains at least SIMULATION_ID, MODEL_ID (node id), MQTT_HOST &amp; MQTT_PORT
   * </pre>
   *
   * <code>repeated .EnvironmentVariable environmentVariables = 3;</code>
   */
  nl.tno.simulation.externalmodel.protos.EnvironmentVariableOrBuilder getEnvironmentVariablesOrBuilder(
      int index);
}
