// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

public interface ModelHasTerminatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModelHasTerminated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TerminationStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.TerminationStatus status = 1;</code>
   * @return The status.
   */
  nl.tno.simulation.externalmodel.protos.TerminationStatus getStatus();

  /**
   * <code>int32 exitCode = 2;</code>
   * @return The exitCode.
   */
  int getExitCode();
}
