// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

public interface NewStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NewStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string parameters_dict = 1;</code>
   * @return The parametersDict.
   */
  java.lang.String getParametersDict();
  /**
   * <code>string parameters_dict = 1;</code>
   * @return The bytes for parametersDict.
   */
  com.google.protobuf.ByteString
      getParametersDictBytes();
}
