// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthcheck.proto

package nl.tno.simulation.externalmodel.protos;

public interface PingHealthSOToMSOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingHealthSOToMSO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.HealthStatus healthy = 1;</code>
   * @return The enum numeric value on the wire for healthy.
   */
  int getHealthyValue();
  /**
   * <code>.HealthStatus healthy = 1;</code>
   * @return The healthy.
   */
  nl.tno.simulation.externalmodel.protos.HealthStatus getHealthy();

  /**
   * <pre>
   * Why is SO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @return A list containing the reasons.
   */
  java.util.List<java.lang.String>
      getReasonsList();
  /**
   * <pre>
   * Why is SO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @return The count of reasons.
   */
  int getReasonsCount();
  /**
   * <pre>
   * Why is SO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @param index The index of the element to return.
   * @return The reasons at the given index.
   */
  java.lang.String getReasons(int index);
  /**
   * <pre>
   * Why is SO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reasons at the given index.
   */
  com.google.protobuf.ByteString
      getReasonsBytes(int index);

  /**
   * <code>repeated string activeSimulations = 3;</code>
   * @return A list containing the activeSimulations.
   */
  java.util.List<java.lang.String>
      getActiveSimulationsList();
  /**
   * <code>repeated string activeSimulations = 3;</code>
   * @return The count of activeSimulations.
   */
  int getActiveSimulationsCount();
  /**
   * <code>repeated string activeSimulations = 3;</code>
   * @param index The index of the element to return.
   * @return The activeSimulations at the given index.
   */
  java.lang.String getActiveSimulations(int index);
  /**
   * <code>repeated string activeSimulations = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the activeSimulations at the given index.
   */
  com.google.protobuf.ByteString
      getActiveSimulationsBytes(int index);
}
