// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthcheck.proto

package nl.tno.simulation.externalmodel.protos;

/**
 * Protobuf type {@code PingHealthMSOToModel}
 */
public final class PingHealthMSOToModel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PingHealthMSOToModel)
    PingHealthMSOToModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PingHealthMSOToModel.newBuilder() to construct.
  private PingHealthMSOToModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PingHealthMSOToModel() {
    healthy_ = 0;
    reasons_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PingHealthMSOToModel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PingHealthMSOToModel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            healthy_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              reasons_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            reasons_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        reasons_ = reasons_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return nl.tno.simulation.externalmodel.protos.Healthcheck.internal_static_PingHealthMSOToModel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return nl.tno.simulation.externalmodel.protos.Healthcheck.internal_static_PingHealthMSOToModel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel.class, nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel.Builder.class);
  }

  public static final int HEALTHY_FIELD_NUMBER = 1;
  private int healthy_;
  /**
   * <code>.HealthStatus healthy = 1;</code>
   * @return The enum numeric value on the wire for healthy.
   */
  @java.lang.Override public int getHealthyValue() {
    return healthy_;
  }
  /**
   * <code>.HealthStatus healthy = 1;</code>
   * @return The healthy.
   */
  @java.lang.Override public nl.tno.simulation.externalmodel.protos.HealthStatus getHealthy() {
    @SuppressWarnings("deprecation")
    nl.tno.simulation.externalmodel.protos.HealthStatus result = nl.tno.simulation.externalmodel.protos.HealthStatus.valueOf(healthy_);
    return result == null ? nl.tno.simulation.externalmodel.protos.HealthStatus.UNRECOGNIZED : result;
  }

  public static final int REASONS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList reasons_;
  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @return A list containing the reasons.
   */
  public com.google.protobuf.ProtocolStringList
      getReasonsList() {
    return reasons_;
  }
  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @return The count of reasons.
   */
  public int getReasonsCount() {
    return reasons_.size();
  }
  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @param index The index of the element to return.
   * @return The reasons at the given index.
   */
  public java.lang.String getReasons(int index) {
    return reasons_.get(index);
  }
  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reasons at the given index.
   */
  public com.google.protobuf.ByteString
      getReasonsBytes(int index) {
    return reasons_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (healthy_ != nl.tno.simulation.externalmodel.protos.HealthStatus.HEALTHY.getNumber()) {
      output.writeEnum(1, healthy_);
    }
    for (int i = 0; i < reasons_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, reasons_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (healthy_ != nl.tno.simulation.externalmodel.protos.HealthStatus.HEALTHY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, healthy_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < reasons_.size(); i++) {
        dataSize += computeStringSizeNoTag(reasons_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReasonsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel)) {
      return super.equals(obj);
    }
    nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel other = (nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel) obj;

    if (healthy_ != other.healthy_) return false;
    if (!getReasonsList()
        .equals(other.getReasonsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEALTHY_FIELD_NUMBER;
    hash = (53 * hash) + healthy_;
    if (getReasonsCount() > 0) {
      hash = (37 * hash) + REASONS_FIELD_NUMBER;
      hash = (53 * hash) + getReasonsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PingHealthMSOToModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PingHealthMSOToModel)
      nl.tno.simulation.externalmodel.protos.PingHealthMSOToModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nl.tno.simulation.externalmodel.protos.Healthcheck.internal_static_PingHealthMSOToModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nl.tno.simulation.externalmodel.protos.Healthcheck.internal_static_PingHealthMSOToModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel.class, nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel.Builder.class);
    }

    // Construct using nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      healthy_ = 0;

      reasons_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return nl.tno.simulation.externalmodel.protos.Healthcheck.internal_static_PingHealthMSOToModel_descriptor;
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel getDefaultInstanceForType() {
      return nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel.getDefaultInstance();
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel build() {
      nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel buildPartial() {
      nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel result = new nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel(this);
      int from_bitField0_ = bitField0_;
      result.healthy_ = healthy_;
      if (((bitField0_ & 0x00000001) != 0)) {
        reasons_ = reasons_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.reasons_ = reasons_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel) {
        return mergeFrom((nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel other) {
      if (other == nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel.getDefaultInstance()) return this;
      if (other.healthy_ != 0) {
        setHealthyValue(other.getHealthyValue());
      }
      if (!other.reasons_.isEmpty()) {
        if (reasons_.isEmpty()) {
          reasons_ = other.reasons_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureReasonsIsMutable();
          reasons_.addAll(other.reasons_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int healthy_ = 0;
    /**
     * <code>.HealthStatus healthy = 1;</code>
     * @return The enum numeric value on the wire for healthy.
     */
    @java.lang.Override public int getHealthyValue() {
      return healthy_;
    }
    /**
     * <code>.HealthStatus healthy = 1;</code>
     * @param value The enum numeric value on the wire for healthy to set.
     * @return This builder for chaining.
     */
    public Builder setHealthyValue(int value) {
      
      healthy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.HealthStatus healthy = 1;</code>
     * @return The healthy.
     */
    @java.lang.Override
    public nl.tno.simulation.externalmodel.protos.HealthStatus getHealthy() {
      @SuppressWarnings("deprecation")
      nl.tno.simulation.externalmodel.protos.HealthStatus result = nl.tno.simulation.externalmodel.protos.HealthStatus.valueOf(healthy_);
      return result == null ? nl.tno.simulation.externalmodel.protos.HealthStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.HealthStatus healthy = 1;</code>
     * @param value The healthy to set.
     * @return This builder for chaining.
     */
    public Builder setHealthy(nl.tno.simulation.externalmodel.protos.HealthStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      healthy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.HealthStatus healthy = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHealthy() {
      
      healthy_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList reasons_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReasonsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        reasons_ = new com.google.protobuf.LazyStringArrayList(reasons_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @return A list containing the reasons.
     */
    public com.google.protobuf.ProtocolStringList
        getReasonsList() {
      return reasons_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @return The count of reasons.
     */
    public int getReasonsCount() {
      return reasons_.size();
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @param index The index of the element to return.
     * @return The reasons at the given index.
     */
    public java.lang.String getReasons(int index) {
      return reasons_.get(index);
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the reasons at the given index.
     */
    public com.google.protobuf.ByteString
        getReasonsBytes(int index) {
      return reasons_.getByteString(index);
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @param index The index to set the value at.
     * @param value The reasons to set.
     * @return This builder for chaining.
     */
    public Builder setReasons(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReasonsIsMutable();
      reasons_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @param value The reasons to add.
     * @return This builder for chaining.
     */
    public Builder addReasons(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReasonsIsMutable();
      reasons_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @param values The reasons to add.
     * @return This builder for chaining.
     */
    public Builder addAllReasons(
        java.lang.Iterable<java.lang.String> values) {
      ensureReasonsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, reasons_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReasons() {
      reasons_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Why is MSO unhealthy?
     * </pre>
     *
     * <code>repeated string reasons = 2;</code>
     * @param value The bytes of the reasons to add.
     * @return This builder for chaining.
     */
    public Builder addReasonsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReasonsIsMutable();
      reasons_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PingHealthMSOToModel)
  }

  // @@protoc_insertion_point(class_scope:PingHealthMSOToModel)
  private static final nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel();
  }

  public static nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PingHealthMSOToModel>
      PARSER = new com.google.protobuf.AbstractParser<PingHealthMSOToModel>() {
    @java.lang.Override
    public PingHealthMSOToModel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PingHealthMSOToModel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PingHealthMSOToModel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PingHealthMSOToModel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public nl.tno.simulation.externalmodel.protos.PingHealthMSOToModel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

