// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: healthcheck.proto

package nl.tno.simulation.externalmodel.protos;

public interface PingHealthMSOToModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PingHealthMSOToModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.HealthStatus healthy = 1;</code>
   * @return The enum numeric value on the wire for healthy.
   */
  int getHealthyValue();
  /**
   * <code>.HealthStatus healthy = 1;</code>
   * @return The healthy.
   */
  nl.tno.simulation.externalmodel.protos.HealthStatus getHealthy();

  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @return A list containing the reasons.
   */
  java.util.List<java.lang.String>
      getReasonsList();
  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @return The count of reasons.
   */
  int getReasonsCount();
  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @param index The index of the element to return.
   * @return The reasons at the given index.
   */
  java.lang.String getReasons(int index);
  /**
   * <pre>
   * Why is MSO unhealthy?
   * </pre>
   *
   * <code>repeated string reasons = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reasons at the given index.
   */
  com.google.protobuf.ByteString
      getReasonsBytes(int index);
}
