// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

/**
 * Protobuf enum {@code TerminationStatus}
 */
public enum TerminationStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUCCESSFULL = 0;</code>
   */
  SUCCESSFULL(0),
  /**
   * <code>FAILED = 1;</code>
   */
  FAILED(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUCCESSFULL = 0;</code>
   */
  public static final int SUCCESSFULL_VALUE = 0;
  /**
   * <code>FAILED = 1;</code>
   */
  public static final int FAILED_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TerminationStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TerminationStatus forNumber(int value) {
    switch (value) {
      case 0: return SUCCESSFULL;
      case 1: return FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TerminationStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TerminationStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TerminationStatus>() {
          public TerminationStatus findValueByNumber(int number) {
            return TerminationStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return nl.tno.simulation.externalmodel.protos.Lifecycle.getDescriptor().getEnumTypes().get(1);
  }

  private static final TerminationStatus[] VALUES = values();

  public static TerminationStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TerminationStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TerminationStatus)
}

