// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

public interface UnhealthyModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnhealthyModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UnhealthyModelStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.UnhealthyModelStatus status = 1;</code>
   * @return The status.
   */
  nl.tno.simulation.externalmodel.protos.UnhealthyModelStatus getStatus();
}
