// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lifecycle.proto

package nl.tno.simulation.externalmodel.protos;

/**
 * Protobuf enum {@code UnhealthyModelStatus}
 */
public enum UnhealthyModelStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NOPROGRESS = 0;</code>
   */
  NOPROGRESS(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NOPROGRESS = 0;</code>
   */
  public static final int NOPROGRESS_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static UnhealthyModelStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static UnhealthyModelStatus forNumber(int value) {
    switch (value) {
      case 0: return NOPROGRESS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<UnhealthyModelStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      UnhealthyModelStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<UnhealthyModelStatus>() {
          public UnhealthyModelStatus findValueByNumber(int number) {
            return UnhealthyModelStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return nl.tno.simulation.externalmodel.protos.Lifecycle.getDescriptor().getEnumTypes().get(0);
  }

  private static final UnhealthyModelStatus[] VALUES = values();

  public static UnhealthyModelStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private UnhealthyModelStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:UnhealthyModelStatus)
}

