# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: healthcheck.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='healthcheck.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n&nl.tno.simulation.externalmodel.protosB\013HealthcheckP\001'),
  serialized_pb=_b('\n\x11healthcheck.proto\"_\n\x11PingHealthSOToMSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\x12\x19\n\x11\x61\x63tiveSimulations\x18\x03 \x03(\t\"D\n\x11PongHealthMSOToSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\"G\n\x14PingHealthMSOToModel\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\"z\n\x14PongHealthModelToMSO\x12\x1e\n\x07healthy\x18\x01 \x01(\x0e\x32\r.HealthStatus\x12\x0f\n\x07reasons\x18\x02 \x03(\t\x12\x14\n\x0cnumberOfBids\x18\x03 \x01(\x05\x12\x1b\n\x13numberOfAllocations\x18\x04 \x01(\x05**\n\x0cHealthStatus\x12\x0b\n\x07HEALTHY\x10\x00\x12\r\n\tUNHEALTHY\x10\x01\x42\x37\n&nl.tno.simulation.externalmodel.protosB\x0bHealthcheckP\x01\x62\x06proto3')
)

_HEALTHSTATUS = _descriptor.EnumDescriptor(
  name='HealthStatus',
  full_name='HealthStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEALTHY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNHEALTHY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=385,
  serialized_end=427,
)
_sym_db.RegisterEnumDescriptor(_HEALTHSTATUS)

HealthStatus = enum_type_wrapper.EnumTypeWrapper(_HEALTHSTATUS)
HEALTHY = 0
UNHEALTHY = 1



_PINGHEALTHSOTOMSO = _descriptor.Descriptor(
  name='PingHealthSOToMSO',
  full_name='PingHealthSOToMSO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='healthy', full_name='PingHealthSOToMSO.healthy', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reasons', full_name='PingHealthSOToMSO.reasons', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeSimulations', full_name='PingHealthSOToMSO.activeSimulations', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=116,
)


_PONGHEALTHMSOTOSO = _descriptor.Descriptor(
  name='PongHealthMSOToSO',
  full_name='PongHealthMSOToSO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='healthy', full_name='PongHealthMSOToSO.healthy', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reasons', full_name='PongHealthMSOToSO.reasons', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=186,
)


_PINGHEALTHMSOTOMODEL = _descriptor.Descriptor(
  name='PingHealthMSOToModel',
  full_name='PingHealthMSOToModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='healthy', full_name='PingHealthMSOToModel.healthy', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reasons', full_name='PingHealthMSOToModel.reasons', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=259,
)


_PONGHEALTHMODELTOMSO = _descriptor.Descriptor(
  name='PongHealthModelToMSO',
  full_name='PongHealthModelToMSO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='healthy', full_name='PongHealthModelToMSO.healthy', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reasons', full_name='PongHealthModelToMSO.reasons', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numberOfBids', full_name='PongHealthModelToMSO.numberOfBids', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='numberOfAllocations', full_name='PongHealthModelToMSO.numberOfAllocations', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=383,
)

_PINGHEALTHSOTOMSO.fields_by_name['healthy'].enum_type = _HEALTHSTATUS
_PONGHEALTHMSOTOSO.fields_by_name['healthy'].enum_type = _HEALTHSTATUS
_PINGHEALTHMSOTOMODEL.fields_by_name['healthy'].enum_type = _HEALTHSTATUS
_PONGHEALTHMODELTOMSO.fields_by_name['healthy'].enum_type = _HEALTHSTATUS
DESCRIPTOR.message_types_by_name['PingHealthSOToMSO'] = _PINGHEALTHSOTOMSO
DESCRIPTOR.message_types_by_name['PongHealthMSOToSO'] = _PONGHEALTHMSOTOSO
DESCRIPTOR.message_types_by_name['PingHealthMSOToModel'] = _PINGHEALTHMSOTOMODEL
DESCRIPTOR.message_types_by_name['PongHealthModelToMSO'] = _PONGHEALTHMODELTOMSO
DESCRIPTOR.enum_types_by_name['HealthStatus'] = _HEALTHSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingHealthSOToMSO = _reflection.GeneratedProtocolMessageType('PingHealthSOToMSO', (_message.Message,), dict(
  DESCRIPTOR = _PINGHEALTHSOTOMSO,
  __module__ = 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PingHealthSOToMSO)
  ))
_sym_db.RegisterMessage(PingHealthSOToMSO)

PongHealthMSOToSO = _reflection.GeneratedProtocolMessageType('PongHealthMSOToSO', (_message.Message,), dict(
  DESCRIPTOR = _PONGHEALTHMSOTOSO,
  __module__ = 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PongHealthMSOToSO)
  ))
_sym_db.RegisterMessage(PongHealthMSOToSO)

PingHealthMSOToModel = _reflection.GeneratedProtocolMessageType('PingHealthMSOToModel', (_message.Message,), dict(
  DESCRIPTOR = _PINGHEALTHMSOTOMODEL,
  __module__ = 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PingHealthMSOToModel)
  ))
_sym_db.RegisterMessage(PingHealthMSOToModel)

PongHealthModelToMSO = _reflection.GeneratedProtocolMessageType('PongHealthModelToMSO', (_message.Message,), dict(
  DESCRIPTOR = _PONGHEALTHMODELTOMSO,
  __module__ = 'healthcheck_pb2'
  # @@protoc_insertion_point(class_scope:PongHealthModelToMSO)
  ))
_sym_db.RegisterMessage(PongHealthModelToMSO)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
